### PR TITLE
[BugFix] Split button Primary action for Camera and Mic buttons

### LINKED ISSUE #2422: I can't turn on and off the microphone and camera after entering the room with ipad
**Describe the bug; what happened?**
In a sample program using CallWithChatComposite, after joining a group call on an Ipad, tapping the microphone and camera toggle buttons on the ControlBar does not respond. Local video before entering the room can be turned on and off.
at IPad iOS15.7

### PR DESCRIPTION
**Pull request by dmceachernmsft**
# What

image
Add primary action to the split buttons for microphone and camera

# Why
Fixes #2422

Allows touch devices to turn the camera and mic on if they are using CWC composite in desktop formfactor

https://skype.visualstudio.com/SPOOL/_workitems/edit/3122819
# How Tested

Ran locally to demonstrate functionality, will update snapshots as well.

Still have to go to design on icons and text.

### CODE REVIEW

**Comment by alkwa-msft** [comment]
do we want to remove the icons as well? I feel it was easier to figure out what your camera was by looking for the camera icon.

**Comment by edwardlee-msft** [comment]
Do we not have snapshots of splitbuttons being actioned? I don't see any snapshots in the changes for callwithchat splitbuttons controlbar.

File: packages/react-components/src/components/CameraButton.tsx [hunk 1]
```diff
@@ -184,6 +201,28 @@ export const CameraButton = (props: CameraButtonProps): JSX.Element => {
...
+      items: [
+        {
+          key: 'cameraPrimaryAction',
+          text: props.checked ? strings.onSplitButtonPrimaryActionCamera : strings.offSplitButtonPrimaryActionCamera,
+          onClick: () => {
+            onToggleClick();
+          },
+          iconProps: {
+            iconName: props.checked ? 'SplitButtonPrimaryActionCameraOn' : 'SplitButtonPrimaryActionCameraOff',
+            styles: { root: { lineHeight: 0 } }
```
Comment (edwardlee-msft) [inline packages/react-components/src/components/CameraButton.tsx:219]: Should we be adding explicit styles here? 
Possibly extract this out.

**Review by edwardlee-msft — APPROVED** [review]

**Review by carocao-msft — APPROVED** [review]
